/**
 * RootLayout - Layout principal de la aplicación
 * 
 * Este es el layout raíz de Next.js que envuelve todas las páginas de la aplicación.
 * Configura:
 * - Fuentes tipográficas (Geist Sans y Geist Mono)
 * - Metadatos de la página (título y descripción)
 * - Estilos globales
 * - Estructura HTML base
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
        {/* PWA Meta Tags */}
        <meta name="application-name" content="Planiverse" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Planiverse" />
        <meta name="description" content="Tu organizador personal para tareas, calendario, notas y recordatorios" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="theme-color" content="#3B82F6" />
        
        {/* Viewport optimizado para móvil */}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes, viewport-fit=cover" />
        
        {/* PWA Manifest */}
        <link rel="manifest" href="/manifest.json" />
        
        {/* Apple Touch Icons */}
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
        <link rel="apple-touch-icon" sizes="192x192" href="/icon-192x192.png" />
        <link rel="apple-touch-icon" sizes="512x512" href="/icon-512x512.png" />
        
        {/* Favicon */}
        <link rel="icon" type="image/png" sizes="192x192" href="/icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/icon-512x512.png" />
        
        {/* Service Worker Registration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Registrar Service Worker para PWA
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', () => {
                  navigator.serviceWorker.register('/sw.js')
                    .then((registration) => {
                      console.log('SW registrado:', registration.scope);
                    })
                    .catch((error) => {
                      console.log('SW registro falló:', error);
                    });
                });
              }
            `,
          }}
        />
        
        {/* Theme Loader */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // Aplicar modo oscuro antes del primer render para evitar flash
                  var darkMode = localStorage.getItem('planiverse_dark_mode');
                  if (darkMode === 'true') {
                    document.documentElement.classList.add('dark');
                  }

                  // Cargar tema de color basado en rol
                  // El rol puede estar en 'planiverse_role' o dentro de 'planiverse_profiles'
                  let role = localStorage.getItem('planiverse_role');
                  if (!role) {
                    try {
                      const session = JSON.parse(localStorage.getItem('planiverse_session') || 'null');
                      if (session && session.userId) {
                        const profiles = JSON.parse(localStorage.getItem('planiverse_profiles') || '{}');
                        const profile = profiles[session.userId];
                        if (profile && profile.role) role = profile.role;
                      }
                    } catch(e) {}
                  }
                  if (role) {
                    const themes = {
                      student: {
                        primary: '#3B82F6',
                        primaryHover: '#2563EB',
                        primaryActive: '#1D4ED8',
                        secondary: '#10B981',
                        accent: '#06B6D4',
                        background: '#F0F9FF',
                        text: '#1E293B',
                        textSecondary: '#64748B'
                      },
                      teacher: {
                        primary: '#F97316',
                        primaryHover: '#EA580C',
                        primaryActive: '#C2410C',
                        secondary: '#EF4444',
                        accent: '#F59E0B',
                        background: '#FFF7ED',
                        text: '#1E293B',
                        textSecondary: '#64748B'
                      },
                      other: {
                        primary: '#8B5CF6',
                        primaryHover: '#7C3AED',
                        primaryActive: '#6D28D9',
                        secondary: '#EC4899',
                        accent: '#A855F7',
                        background: '#FAF5FF',
                        text: '#1E293B',
                        textSecondary: '#64748B'
                      }
                    };
                    
                    const theme = themes[role] || themes.student;
                    const root = document.documentElement;
                    
                    root.style.setProperty('--color-primary', theme.primary);
                    root.style.setProperty('--color-primary-hover', theme.primaryHover);
                    root.style.setProperty('--color-primary-active', theme.primaryActive);
                    root.style.setProperty('--color-secondary', theme.secondary);
                    root.style.setProperty('--color-accent', theme.accent);
                    root.style.setProperty('--color-background', theme.background);
                    root.style.setProperty('--color-text', theme.text);
                    root.style.setProperty('--color-text-secondary', theme.textSecondary);
                    root.setAttribute('data-theme', role);
                  }
                } catch (e) {
                  // Silently fail
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
